### ISSUE TITLE
Custom Skin from custom resource pack won't appear in the skin selection menu

### ISSUE THREAD

**Issue by jakeyhanna** [RedRain0o0/legacy-skins#11]
I have made a resource pack with everything according to the wiki

My skin works in the game when i click it but When i am in the menu hovering i don't see my skin and only see it's description and name

And weirdly the game gets laggy when i am in the pack with the model/skin in it

![image](https://github.com/user-attachments/assets/d0f1752e-4c46-42cd-9b06-3bea5b37c5a5)

I have tried to use models from other resource packs made for the mod with them rending like the pig model

Is there something i am doing wrong in the Exporting process in CPM Or should i do something extra????

**Comment by RedRain0o0** [comment]
did you enable anything like UUID lock?

**Comment by jakeyhanna** [comment]
> did you enable anything like UUID lock?

Okay so i managed to fix this for anyone wondering

I ended up using Blockbench instead of the mod's editor and that seemed to have fixed the problem!
